FROM openjdk:8
RUN mkdir /home/app
ADD target/basement-0.0.1-SNAPSHOT.jar /home/app/basement.jar

ENV JAVA_OPTS="\
-server \
-XX:InitialHeapSize=256m \
-XX:MaxHeapSize=512m \
-XX:MaxNewSize=64m \
-verbose:gc \
-Xloggc:/home/app/gc/gc.log \
-XX:+UseG1GC \
-XX:+PrintGCDetails \
-XX:+PrintGCTimeStamps \
-XX:+PrintGCDateStamps \
-XX:+HeapDumpOnOutOfMemoryError \
-XX:+PrintTLAB \
-XX:+UseGCLogFileRotation \
-XX:+UseCompressedClassPointers \
-XX:+UseCompressedOops \
-XX:+PrintStringDeduplicationStatistics \
-XX:+UseStringDeduplication \
-XX:+PrintContainerInfo \
-XX:NumberOfGCLogFiles=8 \
-XX:ParallelGCThreads=2 \
-XX:NativeMemoryTracking=detail \
-XX:MaxGCPauseMillis=100 \
-XX:GCTimeRatio=19"

RUN echo "#!bin/bash \n java ${JAVA_OPTS} -jar /home/app/basement.jar " > ./start_up.sh
RUN chmod u+x ./start_up.sh

ENTRYPOINT ["./start_up.sh"]