apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  java_opts: >
    -XX:InitialHeapSize=256m
    -XX:MaxHeapSize=512m
    -XX:MaxNewSize=64m
    -Xloggc:/home/app/gc/gc.log
    -XX:+PrintGCDetails
    -XX:+PrintGCTimeStamps
    -XX:+PrintGCDateStamps
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+UseG1GC
    -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=5
    -XX:+UseCompressedClassPointers
    -XX:+UseCompressedOops
    -XX:+UseStringDeduplication
    -XX:ParallelGCThreads=2
    -XX:MaxGCPauseMillis=50
    -XX:GCTimeRatio=29