apiVersion: v1
kind: Service
metadata:
  name: basement
spec:
  type: NodePort
  # 通过 selector 选择 service 对应的 pod
  selector:
    app: basement
  ports:
    - port: 8081
      # 应用的端口
      targetPort: 8081
      # 通过 NodePort 对外暴露的端口
      nodePort: 30007